[package]
name = "blog_os"
version = "0.1.0"
authors = ["taiyoslime <t@iyosli.me>"]
edition = "2018"

[dependencies]
rlibc = "1.0.0"
bootloader = "0.9.8"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"